// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Globalization", "CA2101:Specify marshaling for P/Invoke string arguments", Justification = "<Pending>", Scope = "member", Target = "~M:WinInstaller.Tool.Extensions.IconExtension.Kernel32.LoadLibraryEx(System.String,System.IntPtr,WinInstaller.Tool.Extensions.IconExtension.LOAD_LIBRARY)~System.IntPtr")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:WinInstaller.Tool.Extensions.IconExtension.Kernel32.SizeofResource(System.IntPtr,System.IntPtr)~System.UInt32")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:WinInstaller.Tool.Extensions.IconExtension.Kernel32.LockResource(System.IntPtr)~System.IntPtr")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:WinInstaller.Tool.Extensions.IconExtension.Kernel32.LoadResource(System.IntPtr,System.IntPtr)~System.IntPtr")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:WinInstaller.Tool.Extensions.IconExtension.Kernel32.LoadLibraryEx(System.String,System.IntPtr,WinInstaller.Tool.Extensions.IconExtension.LOAD_LIBRARY)~System.IntPtr")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:WinInstaller.Tool.Extensions.IconExtension.Kernel32.FreeLibrary(System.IntPtr)~System.Boolean")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:WinInstaller.Tool.Extensions.IconExtension.Kernel32.EnumResourceNames(System.IntPtr,WinInstaller.Tool.Extensions.IconExtension.RT,WinInstaller.Tool.Extensions.IconExtension.EnumResNameProcDelegate,System.IntPtr)~System.Boolean")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:WinInstaller.Tool.Extensions.IconExtension.Kernel32.FindResource(System.IntPtr,System.IntPtr,WinInstaller.Tool.Extensions.IconExtension.RT)~System.IntPtr")]
